boot.o: boot.S multiboot.h x86_desc.h types.h
device_handlers.o: device_handlers.S
idt_asm.o: idt_asm.S
x86_desc.o: x86_desc.S x86_desc.h types.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c idt.h types.h x86_desc.h lib.h idt_asm.h device_handlers.h \
  rtc.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h idt.h idt_asm.h rtc.h
keyboard.o: keyboard.c
lib.o: lib.c lib.h types.h
rtc.o: rtc.c rtc.h types.h i8259.h lib.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h
