boot.o: boot.S multiboot.h x86_desc.h types.h
device_handlers.o: device_handlers.S
idt_asm.o: idt_asm.S
paging_asm.o: paging_asm.S
syscall_asm.o: syscall_asm.S
x86_desc.o: x86_desc.S x86_desc.h types.h
exception_handlers.o: exception_handlers.c exception_handlers.h types.h \
  lib.h
file_system.o: file_system.c file_system.h types.h lib.h multiboot.h \
  rtc.h syscall.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c idt.h types.h x86_desc.h lib.h idt_asm.h device_handlers.h \
  rtc.h syscall_asm.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h idt.h idt_asm.h rtc.h keyboard.h paging.h file_system.h \
  syscall.h pit.h
keyboard.o: keyboard.c lib.h types.h i8259.h keyboard.h terminal.h
lib.o: lib.c lib.h types.h
paging.o: paging.c paging.h types.h paging_asm.h lib.h x86_desc.h
pit.o: pit.c pit.h types.h idt.h lib.h i8259.h syscall.h file_system.h \
  multiboot.h
rtc.o: rtc.c rtc.h types.h i8259.h lib.h keyboard.h
syscall.o: syscall.c syscall.h types.h file_system.h lib.h multiboot.h \
  syscall_asm.h paging.h rtc.h terminal.h x86_desc.h
terminal.o: terminal.c keyboard.h types.h lib.h terminal.h rtc.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h paging.h idt_asm.h \
  terminal.h keyboard.h rtc.h syscall.h file_system.h multiboot.h
